### ISSUE TITLE
Azure disk driver test cases summary

### ISSUE THREAD

**Issue by andyzhangx** [kubernetes-sigs/azuredisk-csi-driver#189]
**Is your feature request related to a problem?/Why is this needed**

**Describe the solution you'd like in detail**

## unit tests 
tests to add: 
   - [x] [add windows build test](https://github.com/kubernetes-sigs/azuredisk-csi-driver/issues/217)
   - [ ] [regression unit tests addressing azure disk dirty cache issue](https://github.com/kubernetes/kubernetes/issues/85160)

note:
since azure disk csi driver and in-tree driver use the same azure cloud provider lib, unit tests could be applied to both csi and in-tree drivers.

## e2e tests
Currently there are no e2e tests on in-tree azure disk & file drivers, we could leverage existing csi e2e tests and enable those e2e tests, run against on both csi driver and in-tree driver.

current test cases:
 - should create a volume on demand
 - should create a raw block volume on demand
 - should create a volume on demand and mount it as readOnly in a pod
 - should create multiple PV objects, bind to PVCs and attach all to different pods on the same node
 - should create a deployment object, write and read to it, delete the pod and write and read to it again
 - should delete PV with reclaimPolicy
 - should retain PV with reclaimPolicy
 - cloning a volume from an existing volume

more cases to add:
  - [ ] [Add more e2e test cases](https://github.com/kubernetes-sigs/azuredisk-csi-driver/issues/206)
  - [x] [Add mount options e2e test ](https://github.com/kubernetes-sigs/azuredisk-csi-driver/issues/198)
  - [ ] [Add e2e test for snapshot feature](https://github.com/kubernetes-sigs/azuredisk-csi-driver/issues/146)
  - [ ] [add e2e test for volume expansion feature](https://github.com/kubernetes-sigs/azuredisk-csi-driver/issues/218)
  - [ ] [implement migration test from in-tree driver to CSI driver](https://github.com/kubernetes-sigs/azuredisk-csi-driver/issues/194)
  - [x] [add in-tree driver e2e test](https://github.com/kubernetes-sigs/azuredisk-csi-driver/issues/161)
  - [x] [add e2e zone test case](https://github.com/kubernetes-sigs/azuredisk-csi-driver/issues/179)

## Performance tests
https://github.com/kubernetes-sigs/azuredisk-csi-driver/issues/147

**Describe alternatives you've considered**

**Additional context**

cc @kkmsft @chewong pls add related working PR and issue links into this summary page.

**Comment by kdanW** [comment]
@andyzhangx I see these issues listed in the project under the community bridge program (https://github.com/cncf/soc/tree/master/communitybridge#participating-projects). Do you have any information on what exactly to be done and what can I start with as good first issues?
I am familiar with Kubernetes but not with core Kubernetes code base. If this project is not assigned to anybody I would like to try to work on it. Can you provide me more information please?

**Comment by andyzhangx** [comment]
hi @kdanW this is a summary issue, I think you could fix other issues, here is the list: https://github.com/kubernetes-sigs/azuredisk-csi-driver/issues?q=is%3Aissue+is%3Aopen+label%3A%22help+wanted%22

**Comment by kdanW** [comment]
hi @andyzhangx. I am a little confused about the project. Is it to fix the issues given in the above link? If not, what is the project?
If it is required to create a project proposal, can i have some more information? Is there anyway to contact a mentor on the Slack channel or any other media?

**Comment by andyzhangx** [comment]
@kdanW I see, you found this project by CNCF program. There is already a student working on this project now. My contact: slack: andyzhang @kubernetes

**Comment by kdanW** [comment]
oh alright @andyzhangx . Do you have any other projects in community bridge under Kubernetes?

**Comment by andyzhangx** [comment]
> oh alright @andyzhangx . Do you have any other projects in community bridge under Kubernetes?

@kdanW sorry, I only have this one.

**Comment by kdanW** [comment]
> > oh alright @andyzhangx . Do you have any other projects in community bridge under Kubernetes?
> 
> @kdanW sorry, I only have this one.

No problem. Thanks
